title: Sanjiv Jha
theme: jekyll-theme-minimal
email:jhasanjiv5@gmail.com
social:
  - title: linkedIn
    url: https://www.linkedin.com/in/sanjiv-jha-46793853/
  - title: github
    url: https://github.com/jhasanjiv5