title: Sanjiv Jha
email: jhasanjiv5@gmail.com
description: Contact information 
theme: jekyll-theme-minimal

social:
  - title: linkedIn
    url: https://www.linkedin.com/in/sanjiv-jha-46793853/
  - title: github
    url: https://github.com/jhasanjiv5