title: Sanjiv Jha
email: jhasanjiv5@gmail.com

theme: jekyll-theme-minimal

social:
  - title: linkedIn
    url: https://www.linkedin.com/in/sanjiv-jha-46793853/
  - title: github
    url: https://github.com/jhasanjiv5